### PR TITLE
143 services streamfield options tweak

### PR DESCRIPTION
**Pull request by helenb**
Please could this be merged to master and deployed. Change to make 2 streamfield fields optional.

### CODE REVIEW

**Comment by helenb** [comment]
@nimasmi have now updated the templates as well.

**Comment by nimasmi** [comment]
Merged, thanks. I'll cherry-pick your merge migration from staging.

**Comment by nimasmi** [comment]
Ah, merge migration wasn't necessary: staging is just in a dirty state.

Bad staging. Dirty staging.

**Comment by helenb** [comment]
Ah yes - I mentioned to Tom T earlier that it would be good to replace staging completely with what is now on master.

**Pull request merged**
