### PR TITLE
Make next/previous blog post query only look at siblings

### PR DESCRIPTION
**Pull request by kaedroho**

### CODE REVIEW

**Comment by zerolab** [comment]
Is this still relevant?

**Comment by kaedroho** [comment]
Not sure, but the fact that master merged into it without conflict shows that the code this is fixing hasn't been changed since this PR was created

**Comment by zerolab** [comment]
@kaedroho @tm-kn is this still needed?

**Comment by zerolab** [comment]
Closing as no longer relevant in the new headless setup

**Pull request closed without merging**
