### PR TITLE
221 frontend tooling

### PR DESCRIPTION
**Pull request by hippogriffic**
This needs testing on staging before it gets merged

updates frontend tooling to the latest set up from wagtail kit
- removes gulp in favour of npm scripts
- uses node-sass, webpack

needs backend to look in the right place for static files

then needs testing to make sure compiled files are working correctly

### CODE REVIEW

**Comment by hippogriffic** [comment]
@SimonDEvans not sure if code review is really possible here, but perhaps you can double check staging to make sure everything is working as expected? Currently staging is broken but @tm-kn is on it next week

**Comment by hippogriffic** [comment]
this branch has conflicts in `base.py` which I'm not confident resolving without backend taking a look

**Comment by hippogriffic** [comment]
@tm-kn that's not going to work, there are changes to `base.py` in this branch because the location of static files has been moved, I'm not confident enough to merge the changes from master without reverting the changes we need from this branch

**Comment by tm-kn** [comment]
@hippogriffic I've pushed to branch `221-frontend-tooling-merge`

**Comment by hippogriffic** [comment]
ok shall we close this pr and merge that branch then?

**Pull request merged**
