### PR TITLE
WIP: 215 add links to streamfield blocks

### PR DESCRIPTION
**Pull request by jafacakes2011**
> I need to be able to link to external links or internal pages in all streamfield blocks within the service pages - **Will H**

### CODE REVIEW

**Comment by jafacakes2011** [comment]
I have tested this change locally and it adds the needed functionality, the only issue I can see is that the Rich text block looks strange for an editor.

screen shot 2018-06-22 at 16 32 50

**Comment by richbrennan** [comment]
LGTM

**Comment by jafacakes2011** [comment]
Can this be merged to staging so it can be reviewed?

**Comment by martycoote** [comment]
FE changes waiting for code review.

**Comment by helenb** [comment]
Shame we have to duplicate the styles, but if there is no way to add a class to the rich-text div then we'll have to live with that. LGTM.

**Pull request merged**
