### PR TITLE
Use text and svg for "Made with Wagtail" footer

### PR DESCRIPTION
**Pull request by alexgleason**
Here's a screenshot from my 3K laptop screen:

screenshot from 2016-05-03 15 21 48

It's now selectable text except for "wagtail" which uses an SVG background.

### CODE REVIEW

**Comment by zerolab** [comment]
@helenb can you please review/update?

**Comment by helenb** [comment]
Just reviewing the commits and I see there are no scss files here - only css ones. Also since the original screenshot the footer has changed - although this update to use text rather than an image for the wagtail part still applies. It might be easier for me to add these changes in to a new branch by hand.

**Comment by zerolab** [comment]
Yes please

**Comment by helenb** [comment]
Have now extracted and adapted this code in 129-made-with-wagtail-footer which I will pass over to Ashley to approve.

**Pull request closed without merging**
