### PR TITLE
WIP: 216 add paragraph to service page

### PR DESCRIPTION
**Pull request by victoriachan**
Just a small change from June but needed to redeploy to staging after wagtail upgrade. Realised I didn't get code review for it then. 

Do I commit the migration? On this site since there is only one core app, the chances of your migration falling behind (ie, not the latest number) before you can deploy to live is quite high.

### CODE REVIEW

**Comment by victoriachan** [comment]
Oops sorry, will reassign to Rich to do code review since he is on support tomorrow.

**Comment by richbrennan** [comment]
You should commit migrations, and yes that is a problem with sites with too few apps. 

This build is failing CI due to a missing merge migration, suggesting that migrations have been created on more than one feature branch https://travis-ci.org/torchbox/wagtail-torchbox/builds/422137735

**Comment by richbrennan** [comment]
> the chances of your migration falling behind (ie, not the latest number) before you can deploy to live is quite high.

Best to merge master into your feature branch regularly. If there's a migration clash and you haven't pushed your feature branch or merged into any others then you can delete yours, grab another copy of the DB and create another. If you have pushed or merged you can create a merge migration

**Comment by richbrennan** [comment]
Code changes look fine tho, thanks

**Comment by victoriachan** [comment]
Argh, migration nightmare. I'm just going to create a new branch `216-staging` based on this branch but with `staging` merged into it, and then deploy to staging that branch. When later we want to deploy to live, we'll deploy this branch instead.

**Comment by victoriachan** [comment]
Closing merge request to manually merge so I could squash the commits. Only just realised the button here has a squash and commit option too. Will use that next time, sorry.

**Pull request closed without merging**
