### PR TITLE
Bump Wagtail to 2.13rc3

### PR DESCRIPTION
**Pull request by tbrlpld**
This just came out with fixes for the commenting system. 

No additional upgrade considerations. 

https://pypi.org/project/wagtail/2.13rc3/

https://wagtailcms.slack.com/archives/C0K2WLTRS/p1619700066047300

### CODE REVIEW

**Review by tomdyson — APPROVED** [review]

**Comment by tbrlpld** [comment]
Thanks for reviewing @tomdyson

**Comment by zerolab** [comment]
I suggest bumping to 2.13 and folding #330 into this

**Comment by zerolab** [comment]
@tbrlpld with 2.13 fully out, could you update this PR and then let's get it out. Thank you

**Comment by tbrlpld** [comment]
This is outdated now.

**Pull request closed without merging**
