### PR TITLE
Fix js error

### PR DESCRIPTION
**Pull request by zerolab**

### CODE REVIEW

**Comment by nimasmi** [comment]
Sorry Toby, that I've not looked at this sooner, and this code has now gone stale. I'm not sure which changes are from yours and other commits in main.js. Can you please merge master into this branch?

**Comment by Loque-** [comment]
I rebased the branch and re-added the change (as it was quicker than trying to resolve the conflict manually) - the conflict was due to the someone very kindly fixing the indentation in the JS file.

**Comment by Loque-** [comment]
The FE assets need to be re-created now this change is in the source, I am going to try and do this on master quickly and commit it there. I have a hunch this won't work due to the git setup.

**Comment by Loque-** [comment]
Sorry for the noise, just improving the fix and generating assets so it can be deployed with less pain.

**Pull request merged**
