### PR TITLE
Jobs page

### PR DESCRIPTION
**Pull request by justinepocock**
Updated jobs page ready for staging

### CODE REVIEW

**Comment by mope** [comment]
Thanks!

**Comment by zerolab** [comment]
I am not entirely clear how this works going forward?

The pull request is created against staging, you merge it, thus closing the PR. Then you are ready to go live, so surely you will not merge staging into master.. So does that warrant another PR? Or is it someone from the tech team responsible for them cherry-picking the commit(s) onto master?

**Comment by kaedroho** [comment]
Here's what I think, I've been doing this on a couple of other projects.

All pull requests created against master. To stage, the PR should be manually merged into staging. When signed off, the PR is merged into master, closing it.

**Comment by mope** [comment]
Karl's right as usual, also you can create a branch in this repo and create a pull request for it (only master and staging are protected now), or you can do it in your own repo if you prefer. Ideally you wouldn't request to merge staging into staging, but as you say I can always cherry-pick or something.

**Comment by zerolab** [comment]
:+1: I second the proposed approach, @kaedroho

**Pull request merged**
