### PR TITLE
3230 | Blog, Events + Team page in HCM 

### PR DESCRIPTION
**Pull request by chris-lawton**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1230243230)

### Description of Changes Made
- Add active, hover and focus states to tags when viewing in High Contrast Mode
- Use correct `is_active` var so `aria-current` works
- Add underline to blog titles and team member names to indicate it's a link in HCM
- Add hover and focus state to blog items and team members in HCM

Note the event listing item shares the same class as the blog listing so will inherit the work done here.

### How to Test
- Local blog page: http://localhost:8000/blog/
- Local team page: http://localhost:8000/team/
- In Chrome Dev Tools, under 'Rendering' is an dropdown to emulate `forced-colors: active`

### Screenshots

<details>
  <summary>Expand to see more</summary>

## Active, hover & focus states on tags, blog items and team members

Screenshot 2023-07-28 at 13 13 12

Screenshot 2023-07-28 at 13 13 16

Screenshot 2023-07-28 at 13 13 34

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [ ] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.
- [ ] Tests and linting passes.
- [ ] Consider updating documentation. If you don't, tell us why.
- [ ] If relevant, list the environments / browsers in which you tested your changes.

### CODE REVIEW

**Comment by helenb** [comment]
Couple of small comments:

- For both light and dark colour schemes, the hover effect on the 'load more posts' button is a little odd - it maybe needs the border-radius removing
- Same query as on other tickets about the hover effect that removes the underline (blog listing, team listing)
- We don't have a hover effect on rich text links in HCM (e.g. http://localhost:8000/team/abigail-hampson/, 'Oxfam GB' link)
-

**Comment by chris-lawton** [comment]
@helenb 

> Same query as on other tickets about the hover effect that removes the underline (blog listing, team listing)

I opted for this as it's a visual difference between the two states in HCM whereas something like changing the colour would not be. What do you think? Is there another way?

**Comment by helenb** [comment]
> I opted for this as it's a visual difference between the two states in HCM whereas something like changing the colour would not be. What do you think? Is there another way?

Maybe thicken the underline?

> > We don't have a hover effect on rich text links in HCM (e.g. http://localhost:8000/team/abigail-hampson/, 'Oxfam GB' link)
> 
> The hover states across the site are quite inconsistent so it might be good to do an overhaul of them. I could remove the underline here as well for HCM pending an answer to the above

I think it would be good to get them more consistent when we have a design overhaul - Anna mentioned this might be quite soon. Worth mentioning this at stand-up.

**Comment by chris-lawton** [comment]
> Maybe thicken the underline?

Good shout! I'll update this and the other MRs for consistency : )

**Pull request merged**
